grails:
    profile: plugin
    codegen:
        defaultPackage: errbuddy
    spring:
        transactionManagement:
            proxies: false
    plugin:
        errbuddy:
          enabled: true
          apiKey: GARBAGE
          threshold: WARN
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
